routes/web.php
<?php

use App\Http\Controllers\CompanyC;
use App\Http\Controllers\DesaC;
use App\Http\Controllers\EmployeeC;
use App\Http\Controllers\KabupatenC;
use App\Http\Controllers\ProvinsiC;
use App\Http\Controllers\KecamatanC;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/employees', EmployeeC::class);
Route::get('/employees/export/', 'EmployeeC@export')->name('exportemployee');

Route::resource('/companies', CompanyC::class);


Route::resource('/provinsi', ProvinsiC::class);
Route::resource('/kabupaten', KabupatenC::class);
Route::resource('/kecamatan', KecamatanC::class);
Route::resource('/desa', DesaC::class);

resources/views/template/footer.blade.php
        <footer>
            <div class="footer clearfix mb-0 text-muted">
                <div class="float-start">
                    <p>2021 &copy; Mazer</p>
                </div>
                <div class="float-end">
                    <p>Crafted with <span class="text-danger"><i class="bi bi-heart"></i></span> by <a
                            href="http://ahmadsaugi.com">A. Saugi</a></p>
                </div>
            </div>
        </footer>
    </div>
</div>

<script src="{{ asset('mazer/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
    <script src="{{ asset('mazer/assets/js/bootstrap.bundle.min.js') }}"></script>

    <script src="{{ asset('mazer/assets/js/main.js') }}"></script>
</body>

</html>

resources/views/template/head.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('mazer/assets/css/bootstrap.css') }}">
    
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>

    <link rel="stylesheet" href="{{ asset('mazer/assets/vendors/perfect-scrollbar/perfect-scrollbar.css') }}">
    <link rel="stylesheet" href="{{ asset('mazer/assets/vendors/bootstrap-icons/bootstrap-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('mazer/assets/css/app.css') }}">
    <link rel="shortcut icon" href="{{ asset('mazer/assets/images/favicon.svg') }}" type="image/x-icon">
</head>

<body>

resources/views/template/sidebar.blade.php
<div id="sidebar" class="active">
    <div class="sidebar-wrapper active">
        <div class="sidebar-header">
            <div class="d-flex justify-content-between">
                <div class="logo">
                    <a href="index.html"><img src="{{ asset('mazer/assets/images/logo/logo.png') }}" alt="Logo" srcset=""></a>
                </div>
                <div class="toggler">
                    <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                </div>
            </div>
        </div>
        <div class="sidebar-menu">
            <ul class="menu">
                <li class="sidebar-title">Menu</li>

                <li class="sidebar-item  ">
                    <a href="{{ route('employees.index') }}" class='sidebar-link'>
                        <i class='bx bxs-contact' ></i>
                        <span>Pegawai</span>
                    </a>
                </li>

                <li class="sidebar-item  ">
                    <a href="{{ route('companies.index') }}" class='sidebar-link'>
                        <i class='bx bx-building'></i>
                        <span>Perusahaan</span>
                    </a>
                </li>

                <li class="sidebar-item  ">
                    <a href="{{ route('provinsi.index') }}" class='sidebar-link'>
                        <i class='bx bx-building'></i>
                        <span>Provinsi</span>
                    </a>
                </li>

                <li class="sidebar-item  ">
                    <a href="{{ route('kabupaten.index') }}" class='sidebar-link'>
                        <i class='bx bx-building'></i>
                        <span>Kabupaten</span>
                    </a>
                </li>

                <li class="sidebar-item  ">
                    <a href="{{ route('kecamatan.index') }}" class='sidebar-link'>
                        <i class='bx bx-building'></i>
                        <span>Kecamatan</span>
                    </a>
                </li>

                <li class="sidebar-item  ">
                    <a href="{{ route('desa.index') }}" class='sidebar-link'>
                        <i class='bx bx-building'></i>
                        <span>Desa</span>
                    </a>
                </li>


            </ul>
        </div>
        <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
    </div>
</div>